export const CONTENT_PACK_VERSION = 'baseline-daily-30-v1';

function unit({id,type='chunk',target,meaning,accepted=[],utility=1,tags=[],source,train,evals}){
  return {
    id,type,canonicalForm:target,meanings:[meaning],accepted,utility,tags,
    encounters:[{
      id:`enc-${id}-1`,sourceType:'curated-baseline',label:'Bộ baseline Nếp',
      originalSentence:source || target,
      note:'Nội dung thử nghiệm được biên tập thủ công; chưa gắn nhãn CEFR hay coi là corpus evidence.'
    }],
    trainContexts:train.map((text,i)=>({id:`train-${id}-${i+1}`,text})),
    evalContexts:evals.map((text,i)=>({id:`eval-${id}-${i+1}`,text})),
  };
}

export const BASELINE_UNITS = [
  unit({id:'pick-up-order',type:'collocation',target:'pick up an order',meaning:'nhận / lấy một đơn hàng',accepted:['pick up the order','pick up my order'],utility:1.05,tags:['delivery','work','phrasal-verb'],source:'I need to pick up an order for Minh.',train:['Bạn tới quầy của nhà hàng để nhận đơn đã chuẩn bị xong. Nói hành động mình cần làm.','Nhân viên hỏi bạn tới nhà hàng làm gì. Nói rằng bạn tới nhận một đơn hàng.'],evals:['Ứng dụng báo đơn đã sẵn sàng tại quán. Nói ngắn gọn việc bạn cần làm tiếp theo.','Bạn giải thích với bảo vệ rằng mình chỉ vào trong để nhận đơn giao hàng.']}),
  unit({id:'on-my-way',target:"I'm on my way.",meaning:'Tôi đang trên đường tới.',accepted:['I am on my way',"I'm on the way",'I am on the way'],utility:1.08,tags:['daily','message'],source:"Don't worry — I'm on my way.",train:['Một người đang đợi và hỏi bạn đang ở đâu. Nhắn rằng bạn đang trên đường tới.','Bạn vừa rời nhà và người kia hỏi bạn đã đi chưa. Trả lời ngắn gọn.'],evals:['Người giao hẹn gặp bạn ở sảnh và hỏi bạn có đang tới không. Trả lời tự nhiên.','Bạn bè nhắn “Are you coming?”. Bạn đã lên xe và đang tới chỗ hẹn.']}),
  unit({id:'running-late',target:"I'm running late.",meaning:'Tôi đang bị trễ / sắp đến muộn.',accepted:['I am running late'],utility:1.1,tags:['daily','message'],source:"Sorry, I'm running late. I'll be there in ten minutes.",train:['Cuộc hẹn bắt đầu trong 5 phút nhưng bạn vẫn còn trên đường. Nhắn một câu ngắn.','Xe của bạn bị kẹt và người kia đang chờ. Báo rằng bạn sẽ tới muộn.'],evals:['Bạn hẹn ở quán cà phê lúc 7 giờ nhưng xe buýt bị chậm. Báo tình hình.','Bạn sắp vào ca làm nhưng vẫn cách chỗ làm 10 phút. Nhắn cho đồng nghiệp.']}),
  unit({id:'say-again',type:'expression',target:'Could you say that again?',meaning:'Bạn có thể nói lại được không?',accepted:['Can you say that again?','Could you repeat that?','Can you repeat that?'],utility:1.18,tags:['survival','conversation'],source:'Sorry, could you say that again?',train:['Bạn không nghe rõ người đối diện. Lịch sự yêu cầu họ nói lại.','Người kia nói quá nhanh. Yêu cầu họ lặp lại.'],evals:['Trong cuộc gọi, âm thanh bị rè và bạn bỏ lỡ câu vừa rồi. Bạn sẽ nói gì?','Nhân viên vừa nói một thông tin nhưng bạn không bắt kịp. Yêu cầu họ nói lại.']}),
  unit({id:'listen-to-music',type:'collocation',target:'listen to music',meaning:'nghe nhạc',accepted:['listen to the music'],utility:.95,tags:['daily','collocation','preposition'],source:'I listen to music when I ride home.',train:['Nói một hoạt động bạn hay làm khi nghỉ ngơi: nghe nhạc.','Hoàn thành ý bằng tiếng Anh: buổi tối tôi thường nghe nhạc.'],evals:['Bạn kể về việc mình thường làm khi đi xe buýt về nhà: nghe nhạc.','Bạn đang nói về thói quen trước khi ngủ và muốn nói mình nghe nhạc.']}),
  unit({id:'dont-understand',type:'expression',target:"I don't understand.",meaning:'Tôi không hiểu.',accepted:['I do not understand'],utility:1.15,tags:['survival','conversation'],source:"Sorry, I don't understand.",train:['Người đối diện giải thích nhưng bạn vẫn không hiểu. Nói thẳng điều đó.','Bạn nghe một hướng dẫn nhưng chưa hiểu. Trả lời ngắn gọn.'],evals:['Một nhân viên nói điều gì đó bạn không hiểu. Bạn sẽ nói gì?','Trong cuộc trò chuyện, bạn mất ý và muốn báo rằng mình chưa hiểu.']}),
  unit({id:'what-do-you-mean',type:'expression',target:'What do you mean?',meaning:'Ý bạn là gì?',accepted:['What do you mean by that?'],utility:1.08,tags:['conversation'],source:'What do you mean? I thought we were leaving now.',train:['Người kia nói một điều mơ hồ. Hỏi họ ý là gì.','Bạn không rõ câu vừa rồi muốn nói điều gì. Hỏi lại.'],evals:['Bạn nhận một tin nhắn khó hiểu và muốn người gửi làm rõ.','Một đồng nghiệp nói “It might not work.” nhưng bạn chưa hiểu cụ thể. Hỏi lại.']}),
  unit({id:'can-you-help-me',type:'expression',target:'Can you help me?',meaning:'Bạn có thể giúp tôi không?',accepted:['Could you help me?'],utility:1.12,tags:['survival'],source:'Excuse me, can you help me?',train:['Bạn đang gặp khó khăn và cần nhờ một người gần đó giúp.','Bạn không biết cách làm tiếp và muốn nhờ hỗ trợ.'],evals:['Bạn bị lạc trong một tòa nhà và muốn nhờ nhân viên hỗ trợ.','Máy thanh toán có vấn đề và bạn muốn nhờ người phụ trách giúp.']}),
  unit({id:'need-some-help',type:'expression',target:'I need some help.',meaning:'Tôi cần một chút giúp đỡ.',accepted:['I need help'],utility:1,tags:['survival'],source:'I need some help with this.',train:['Bạn không tự xử lý được việc đang làm. Nói rằng bạn cần giúp đỡ.','Bạn gọi cho một người quen vì đang cần hỗ trợ.'],evals:['Bạn đang mắc kẹt với một thiết bị và muốn báo mình cần hỗ trợ.','Bạn tới quầy dịch vụ và muốn mở đầu bằng việc nói mình cần giúp.']}),
  unit({id:'give-me-minute',type:'expression',target:'Give me a minute.',meaning:'Cho tôi một phút.',accepted:['Give me one minute','Just give me a minute'],utility:1.02,tags:['daily','conversation'],source:'Give me a minute. I need to check something.',train:['Bạn cần một chút thời gian trước khi trả lời. Nói người kia chờ một phút.','Bạn đang làm dở việc và chưa thể trả lời ngay.'],evals:['Một người hỏi gấp nhưng bạn cần kiểm tra điện thoại trước. Nói gì?','Bạn đang tìm thông tin và cần người kia đợi ngắn.']}),
  unit({id:'let-me-check',type:'expression',target:'Let me check.',meaning:'Để tôi kiểm tra.',accepted:['Let me check that','Let me check it'],utility:1.08,tags:['daily','work'],source:'Let me check. I think the order is ready.',train:['Bạn chưa chắc thông tin và muốn kiểm tra trước khi trả lời.','Có người hỏi trạng thái một việc. Nói bạn sẽ kiểm tra.'],evals:['Khách hỏi một thông tin bạn chưa chắc. Bạn muốn kiểm tra trước.','Đồng nghiệp hỏi đơn đã xong chưa nhưng bạn cần nhìn lại hệ thống.']}),
  unit({id:'not-sure',type:'expression',target:"I'm not sure.",meaning:'Tôi không chắc.',accepted:['I am not sure'],utility:1.08,tags:['daily','conversation'],source:"I'm not sure. Let me check.",train:['Bạn không biết chắc câu trả lời. Nói điều đó ngắn gọn.','Người kia hỏi điều bạn chỉ đoán chứ không chắc.'],evals:['Bạn được hỏi giờ đóng cửa nhưng không nhớ chính xác.','Một người hỏi đường và bạn không chắc hướng nào đúng.']}),
  unit({id:'makes-sense',type:'expression',target:'That makes sense.',meaning:'Điều đó hợp lý / tôi hiểu rồi.',accepted:['It makes sense','That makes sense to me'],utility:.98,tags:['conversation'],source:'Oh, that makes sense now.',train:['Sau khi được giải thích, bạn thấy điều đó hợp lý. Phản hồi tự nhiên.','Người kia giải thích lý do và bạn hiểu ra.'],evals:['Đồng nghiệp giải thích vì sao kế hoạch thay đổi và bạn thấy hợp lý.','Một người làm rõ điều khiến bạn bối rối. Bạn phản hồi rằng giờ đã hiểu.']}),
  unit({id:'it-depends',type:'expression',target:'It depends.',meaning:'Còn tùy.',accepted:['That depends'],utility:1,tags:['conversation'],source:'It depends. What time do you want to go?',train:['Câu trả lời thay đổi tùy tình huống. Nói ngắn gọn “còn tùy”.','Người kia hỏi một câu không thể trả lời có/không ngay.'],evals:['Bạn được hỏi “Is it always busy here?” nhưng câu trả lời tùy giờ.','Bạn được hỏi một kế hoạch có tốt không, nhưng còn tùy điều kiện.']}),
  unit({id:'sounds-good',type:'expression',target:'Sounds good.',meaning:'Nghe ổn đấy / được đó.',accepted:['That sounds good','It sounds good','Sounds good to me'],utility:1.12,tags:['conversation','message'],source:'Seven o’clock? Sounds good.',train:['Người kia đề xuất một kế hoạch và bạn đồng ý.','Bạn nhận một thời gian hẹn phù hợp. Phản hồi tự nhiên.'],evals:['Bạn bè đề xuất gặp ở quán gần nhà lúc 8 giờ và bạn thấy ổn.','Đồng nghiệp đưa ra cách xử lý bạn đồng ý.']}),
  unit({id:'no-problem',type:'expression',target:'No problem.',meaning:'Không vấn đề gì / được thôi.',accepted:['No problem at all'],utility:1.08,tags:['daily','conversation'],source:'No problem. I can wait.',train:['Người kia xin lỗi vì làm bạn chờ và bạn muốn nói không sao.','Ai đó nhờ một việc nhỏ và bạn đồng ý thoải mái.'],evals:['Một người xin lỗi vì đến chậm và bạn không phiền.','Đồng nghiệp cảm ơn vì bạn hỗ trợ một việc nhỏ. Bạn đáp tự nhiên.']}),
  unit({id:'take-your-time',type:'expression',target:'Take your time.',meaning:'Cứ từ từ, không cần vội.',accepted:['You can take your time'],utility:1.02,tags:['daily','conversation'],source:'Take your time. There’s no rush.',train:['Người kia đang vội vì sợ bạn phải chờ. Nói họ cứ từ từ.','Bạn muốn báo rằng không cần gấp.'],evals:['Bạn bè đang tìm đồ và liên tục xin lỗi vì lâu. Nói họ không cần vội.','Một nhân viên đang kiểm tra thông tin và bạn sẵn sàng chờ.']}),
  unit({id:'almost-there',type:'expression',target:"I'm almost there.",meaning:'Tôi gần tới rồi.',accepted:['I am almost there'],utility:1.08,tags:['message','daily'],source:"I'm almost there. Two more minutes.",train:['Người kia hỏi còn bao lâu nữa bạn tới. Bạn đã ở rất gần.','Bạn muốn nhắn rằng chỉ còn một chút nữa là tới nơi.'],evals:['Bạn đã tới gần điểm hẹn và người kia hỏi “Where are you?”.','Bạn còn cách địa điểm giao hàng khoảng một con phố. Báo rằng gần tới.']}),
  unit({id:'right-back',type:'expression',target:"I'll be right back.",meaning:'Tôi sẽ quay lại ngay.',accepted:['I will be right back',"I'll be back in a minute"],utility:1,tags:['daily'],source:"I'll be right back. I need to get my phone.",train:['Bạn rời đi rất ngắn rồi sẽ quay lại. Báo cho người kia.','Bạn cần lấy một món đồ ở phòng bên và sẽ trở lại ngay.'],evals:['Bạn đang nói chuyện nhưng cần ra ngoài lấy đồ trong một phút.','Bạn rời bàn một lúc rất ngắn và muốn người kia biết bạn sẽ quay lại.']}),
  unit({id:'im-ready',type:'expression',target:"I'm ready.",meaning:'Tôi sẵn sàng rồi.',accepted:['I am ready'],utility:.95,tags:['daily'],source:"I'm ready. Let's go.",train:['Mọi người đang chờ bạn để bắt đầu và bạn đã chuẩn bị xong.','Ai đó hỏi bạn đã sẵn sàng chưa. Trả lời khẳng định.'],evals:['Nhóm sắp rời đi và hỏi bạn còn cần thời gian không. Bạn đã xong.','Một buổi tập sắp bắt đầu và người hướng dẫn hỏi bạn sẵn sàng chưa.']}),
  unit({id:'where-restroom',type:'expression',target:'Where is the restroom?',meaning:'Nhà vệ sinh ở đâu?',accepted:["Where's the restroom?",'Where is the bathroom?',"Where's the bathroom?"],utility:1.1,tags:['survival','travel'],source:'Excuse me, where is the restroom?',train:['Bạn đang ở một nơi lạ và cần tìm nhà vệ sinh. Hỏi nhân viên.','Bạn không biết nhà vệ sinh nằm ở đâu. Hỏi lịch sự.'],evals:['Bạn đang ở quán cà phê mới và cần tìm nhà vệ sinh.','Trong trung tâm thương mại, bạn muốn hỏi bảo vệ vị trí nhà vệ sinh.']}),
  unit({id:'how-much',type:'expression',target:'How much is this?',meaning:'Cái này bao nhiêu tiền?',accepted:["How much is it?",'How much does this cost?'],utility:1.08,tags:['shopping','survival'],source:'How much is this?',train:['Bạn cầm một món đồ nhưng không thấy giá. Hỏi nhân viên.','Bạn muốn biết giá của món đồ trước mặt.'],evals:['Ở một quầy nhỏ, món bạn muốn mua không có nhãn giá.','Bạn chỉ vào một sản phẩm và muốn hỏi giá.']}),
  unit({id:'pay-by-card',type:'expression',target:'Can I pay by card?',meaning:'Tôi có thể trả bằng thẻ không?',accepted:['Can I pay with a card?','Do you take cards?','Do you accept cards?'],utility:1.05,tags:['shopping','survival'],source:'Can I pay by card?',train:['Bạn sắp thanh toán và muốn biết cửa hàng có nhận thẻ không.','Bạn không có tiền mặt và muốn hỏi có thể trả bằng thẻ.'],evals:['Sau bữa ăn, bạn muốn thanh toán nhưng chỉ có thẻ.','Ở cửa hàng nhỏ, bạn muốn hỏi họ có nhận thanh toán thẻ không.']}),
  unit({id:'some-water',type:'expression',target:"I'd like some water.",meaning:'Tôi muốn một ít nước.',accepted:['I would like some water','Can I have some water?','Could I have some water?'],utility:1,tags:['food','survival'],source:"I'd like some water, please.",train:['Bạn đang gọi đồ uống và muốn nước.','Nhân viên hỏi bạn muốn uống gì. Trả lời rằng bạn muốn nước.'],evals:['Ở nhà hàng, bạn khát và muốn gọi nước.','Trên chuyến đi, nhân viên hỏi bạn muốn uống gì.']}),
  unit({id:'bill-please',type:'expression',target:'Could I have the bill, please?',meaning:'Cho tôi xin hóa đơn / tính tiền.',accepted:['Can I have the bill, please?','Could we have the bill, please?','Can we have the bill, please?','Could I get the bill, please?'],utility:1.08,tags:['food','travel'],source:'Could I have the bill, please?',train:['Bạn ăn xong ở nhà hàng và muốn thanh toán. Gọi nhân viên.','Bạn muốn xin hóa đơn sau bữa ăn.'],evals:['Bạn và bạn bè chuẩn bị rời quán và cần tính tiền.','Ở cuối bữa ăn, bạn muốn nhân viên mang hóa đơn tới.']}),
  unit({id:'just-looking',type:'expression',target:"I'm just looking.",meaning:'Tôi chỉ xem thôi.',accepted:['I am just looking','Just looking, thanks'],utility:.98,tags:['shopping'],source:"Thanks, I'm just looking.",train:['Nhân viên cửa hàng hỏi có cần giúp không nhưng bạn chỉ đang xem.','Bạn chưa định mua gì và muốn nói mình chỉ xem.'],evals:['Bạn bước vào cửa hàng và nhân viên hỏi “Can I help you?”. Bạn chưa cần hỗ trợ.','Nhân viên bán hàng tiến lại nhưng bạn muốn tiếp tục xem một mình.']}),
  unit({id:'have-question',type:'expression',target:'I have a question.',meaning:'Tôi có một câu hỏi.',accepted:["I've got a question"],utility:.95,tags:['conversation','work'],source:'Excuse me, I have a question.',train:['Bạn muốn hỏi người đang hướng dẫn một điều. Mở đầu tự nhiên.','Bạn cần ngắt nhẹ để đặt câu hỏi.'],evals:['Sau khi nghe hướng dẫn, bạn còn một điều chưa rõ và muốn hỏi.','Trong cuộc họp, bạn muốn báo rằng mình có câu hỏi.']}),
  unit({id:'what-time-start',type:'expression',target:'What time does it start?',meaning:'Nó bắt đầu lúc mấy giờ?',accepted:['What time does this start?','When does it start?'],utility:1,tags:['time','survival'],source:'What time does it start?',train:['Bạn biết có một sự kiện nhưng chưa biết giờ bắt đầu. Hỏi người khác.','Bạn muốn biết chính xác mấy giờ chương trình bắt đầu.'],evals:['Bạn chuẩn bị đi xem một buổi biểu diễn nhưng quên giờ bắt đầu.','Bạn hỏi về một lớp học ngày mai và cần biết giờ bắt đầu.']}),
  unit({id:'stuck-traffic',type:'expression',target:"I'm stuck in traffic.",meaning:'Tôi đang bị kẹt xe.',accepted:['I am stuck in traffic'],utility:1.1,tags:['daily','message','transport'],source:"I'm stuck in traffic. I may be late.",train:['Bạn đang trên đường nhưng xe gần như không di chuyển. Nhắn lý do.','Người kia hỏi vì sao bạn chưa tới. Bạn đang kẹt xe.'],evals:['Bạn đi làm nhưng đường đông nghẹt và cần báo tình hình.','Bạn đang tới cuộc hẹn nhưng giao thông khiến bạn đứng yên lâu.']}),
  unit({id:'battery-low',type:'expression',target:'My battery is low.',meaning:'Pin của tôi sắp hết.',accepted:["My phone's battery is low",'My phone battery is low'],utility:.95,tags:['phone','daily'],source:'My battery is low. I need a charger.',train:['Điện thoại chỉ còn ít pin. Nói tình trạng đó.','Bạn giải thích vì sao có thể mất liên lạc sớm.'],evals:['Bạn còn 5% pin và muốn báo cho người đang nhắn tin với mình.','Bạn cần mượn sạc vì điện thoại gần hết pin. Nói lý do.']}),
  unit({id:'app-not-working',type:'expression',target:"The app isn't working.",meaning:'Ứng dụng không hoạt động.',accepted:['The app is not working',"This app isn't working",'The app does not work'],utility:1.05,tags:['phone','work'],source:"The app isn't working. I can't open the order.",train:['Bạn mở ứng dụng nhưng nó không hoạt động. Báo lỗi.','Người hỗ trợ hỏi vấn đề là gì. Nói rằng app không chạy.'],evals:['Bạn không thể thao tác vì ứng dụng liên tục lỗi. Báo ngắn gọn.','Đồng nghiệp hỏi sao bạn chưa xử lý được. Nguyên nhân là ứng dụng không hoạt động.']}),
  unit({id:'order-not-ready',type:'expression',target:"The order isn't ready yet.",meaning:'Đơn hàng vẫn chưa sẵn sàng.',accepted:['The order is not ready yet',"The order isn't ready",'The order is not ready'],utility:1.12,tags:['delivery','work'],source:"The order isn't ready yet. It'll take five more minutes.",train:['Bạn tới quán nhưng nhân viên vẫn đang chuẩn bị đơn. Báo tình trạng.','Có người hỏi bạn đã lấy được đơn chưa nhưng quán chưa làm xong.'],evals:['Bạn đang chờ ở nhà hàng và cần báo rằng đơn vẫn chưa sẵn sàng.','Ứng dụng hỏi trạng thái lấy hàng, nhưng nhân viên nói cần thêm vài phút.']}),
];
